{
    "timestamp": "2025-03-03T02:49:00.768228054Z",
    "level": "ERROR",
    "module": "DatabaseModule",
    "message": "Database connection failed",
    "context": {
        "error": "Timeout"
    },
    "source": {
        "file": "C:\\xampp\\htdocs\\public\\index.php",
        "line": 57
    },
    "trace_id": null,
    "error_details": null,
    "metadata": []
}
